# -*- coding: utf-8 -*-
# Generated by Django 5.0.6 on 2024-05-16 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quickcarthome", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="banner",
            options={"ordering": ["id"], "verbose_name": "Banner Details"},
        ),
    ]
