# -*- coding: utf-8 -*-
# Generated by Django 5.0.6 on 2024-05-21 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quickcarthome", "0002_alter_banner_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="banner",
            old_name="banner_image",
            new_name="image",
        ),
    ]
