# -*- coding: utf-8 -*-
# Generated by Django 5.0.6 on 2024-05-15 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offer",
                to="products.category",
            ),
            preserve_default=False,
        ),
    ]
