# -*- coding: utf-8 -*-
# Generated by Django 5.0.6 on 2024-05-16 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_offer_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="product", to="products.category"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="offer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product",
                to="products.offer",
            ),
        ),
    ]
