# -*- coding: utf-8 -*-
# Generated by Django 5.0.6 on 2024-05-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_product_category_alter_product_offer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["id"], "verbose_name": "Product Category"},
        ),
        migrations.AlterModelOptions(
            name="offer",
            options={"ordering": ["id"], "verbose_name": "Product Discount"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["id"], "verbose_name": "Product"},
        ),
        migrations.AlterModelOptions(
            name="productimage",
            options={"ordering": ["id"], "verbose_name": "Product Images"},
        ),
        migrations.AddField(
            model_name="productimage",
            name="image_1_alt",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="productimage",
            name="image_2_alt",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="productimage",
            name="image_3_alt",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="productimage",
            name="image_4_alt",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ManyToManyField(
                blank=True, related_name="product", to="products.category"
            ),
        ),
    ]
