# -*- coding: utf-8 -*-
# Generated by Django 5.0.6 on 2024-05-16 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_alter_category_options_alter_offer_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image_1_alt",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Image 1 Alt Text"
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image_2_alt",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Image 2 Alt Text"
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image_3_alt",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Image 3 Alt Text"
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image_4_alt",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Image 4 Alt Text"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product",
                to="products.category",
            ),
        ),
    ]
