# -*- coding: utf-8 -*-
# Generated by Django 5.0.6 on 2024-05-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_alter_productimage_image_1_alt_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image_1",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to="Product Images",
                verbose_name="Product Image 1",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image_2",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to="Product Images",
                verbose_name="Product Image 2",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image_3",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to="Product Images",
                verbose_name="Product Image 3",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image_4",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to="Product Images",
                verbose_name="Product Image 4",
            ),
        ),
    ]
