# -*- coding: utf-8 -*-
# Generated by Django 5.0.6 on 2024-05-17 17:57

import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_alter_productimage_image_1_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="image",
            field=models.ImageField(
                blank=True, max_length=1024, null=True, upload_to="Offer Images"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="view_count",
            field=models.PositiveIntegerField(default=0, verbose_name="View Count"),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image_1",
            field=models.ImageField(
                blank=True,
                max_length=1024,
                null=True,
                upload_to="Product Images",
                verbose_name="Product Image 1",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image_1_alt",
            field=models.CharField(
                blank=True, max_length=4096, null=True, verbose_name="Image 1 Alt Text"
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image_2",
            field=models.ImageField(
                blank=True,
                max_length=1024,
                null=True,
                upload_to="Product Images",
                verbose_name="Product Image 2",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image_2_alt",
            field=models.CharField(
                blank=True, max_length=4096, null=True, verbose_name="Image 2 Alt Text"
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image_3",
            field=models.ImageField(
                blank=True,
                max_length=1024,
                null=True,
                upload_to="Product Images",
                verbose_name="Product Image 3",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image_3_alt",
            field=models.CharField(
                blank=True, max_length=4096, null=True, verbose_name="Image 3 Alt Text"
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image_4",
            field=models.ImageField(
                blank=True,
                max_length=1024,
                null=True,
                upload_to="Product Images",
                verbose_name="Product Image 4",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image_4_alt",
            field=models.CharField(
                blank=True, max_length=4096, null=True, verbose_name="Image 4 Alt Text"
            ),
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review",
                        to="products.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
    ]
