# -*- coding: utf-8 -*-
# Generated by Django 5.0.6 on 2024-05-17 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_offer_image_product_user_product_view_count_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={"ordering": ["created"], "verbose_name": "Products Review"},
        ),
    ]
