# -*- coding: utf-8 -*-
# Generated by Django 5.0.6 on 2024-05-18 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0011_alter_review_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="offer",
            options={"ordering": ["id"], "verbose_name": "Offers"},
        ),
    ]
