# -*- coding: utf-8 -*-
# Generated by Django 5.0.6 on 2024-05-22 09:17

import django.db.models.deletion
import mptt.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0013_alter_offer_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="subcategory",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategories",
                to="products.category",
            ),
        ),
    ]
