# -*- coding: utf-8 -*-
# Generated by Django 5.0.6 on 2024-05-22 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0014_alter_category_subcategory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="subcategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategories",
                to="products.category",
            ),
        ),
    ]
